# Generated by Django 4.1 on 2024-03-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dex',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('desc', models.TextField()),
                ('dex', models.CharField(max_length=22)),
                ('cake_day', models.DateField()),
                ('propic', models.CharField(max_length=100)),
                ('rules', models.TextField()),
                ('cover', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('username', models.CharField(max_length=22)),
                ('cake_day', models.DateField()),
                ('desc', models.TextField()),
                ('propic', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=50)),
                ('cover', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('cake_day', models.DateTimeField()),
                ('file', models.CharField(default=None, max_length=200)),
                ('upvote', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('downvote', models.IntegerField(default=0)),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.dex')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
            ],
        ),
        migrations.AddField(
            model_name='dex',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('cake_day', models.DateTimeField()),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.dex')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.post')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.dex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
            ],
            options={
                'unique_together': {('user', 'dex')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.dex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
            ],
            options={
                'unique_together': {('user', 'dex')},
            },
        ),
    ]
