# Generated by Django 5.0.3 on 2024-03-13 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dex',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('desc', models.CharField(max_length=50)),
                ('dex', models.CharField(max_length=22)),
                ('cake_day', models.DateField()),
                ('propic', models.ImageField(upload_to='static/prodex_pics/')),
                ('cover', models.ImageField(upload_to='static/covers/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=22)),
                ('username', models.CharField(max_length=22)),
                ('cake_day', models.DateField()),
                ('propic', models.ImageField(upload_to='static/profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('rfid', models.BigAutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='static/data/')),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.dex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
            ],
        ),
    ]
