# Generated by Django 5.0.3 on 2024-03-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dex',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
