# Generated by Django 5.0.3 on 2024-03-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0002_dex_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dex',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
