# Generated by Django 5.0.3 on 2024-03-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0003_alter_dex_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dex',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
