# Generated by Django 5.0.3 on 2024-03-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0004_remove_dex_email_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dex',
            name='propic',
            field=models.CharField(max_length=200),
        ),
    ]
