# Generated by Django 5.0.3 on 2024-03-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0005_alter_dex_propic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dex',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='DexBS.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dex',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dex',
            name='propic',
            field=models.ImageField(upload_to='static/dex_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('cake_day', models.DateTimeField()),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.dex')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.post')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.dex')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexBS.user')),
            ],
            options={
                'unique_together': {('user', 'dex')},
            },
        ),
    ]
