# Generated by Django 5.0.3 on 2024-03-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0006_dex_owner_post_downvote_post_upvote_alter_dex_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover',
            field=models.FileField(default=None, upload_to='static/user_cover/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dex',
            name='cover',
            field=models.ImageField(upload_to='static/dex_covers/'),
        ),
    ]
