# Generated by Django 5.0.3 on 2024-03-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0007_user_cover_user_desc_alter_dex_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.CharField(max_length=7),
        ),
    ]
