# Generated by Django 5.0.3 on 2024-03-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0008_alter_user_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dex',
            name='cover',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='dex',
            name='propic',
            field=models.ImageField(upload_to='static/dex_pics'),
        ),
    ]
