# Generated by Django 5.0.3 on 2024-03-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0009_alter_dex_cover_alter_dex_propic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='propic',
            field=models.CharField(max_length=10000),
        ),
    ]
