# Generated by Django 5.0.3 on 2024-03-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexBS', '0010_alter_user_propic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislike',
            new_name='downvote',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='like',
            new_name='upvote',
        ),
        migrations.AddField(
            model_name='dex',
            name='rules',
            field=models.TextField(default='No Rules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dex',
            name='rules_desc',
            field=models.TextField(default='No Rules'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='cake_day',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dex',
            name='propic',
            field=models.ImageField(upload_to='d/dex_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(upload_to='post/data/'),
        ),
    ]
